# Header
menu:
  首页: /
  归档: /archives
rss:

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- archive
- tagcloud
- tag
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: yanni4night
google_plus: yanni4night@gmail.com
fb_admins:
fb_app_id: