# Header
menu:
  首页: /
  归档: /archives
  GitHub: https://github.com/yanni4night
  Twitter: https://twitter.com/yanni4night
  Instagram: https://www.instagram.com/yanni4night/
  Gmail: mailto:yanni4night@gmail.com
  PantoJS: http://pantojs.xyz/
rss:

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- archive
- tagcloud
- tag
- recent_posts

# Miscellaneous
google_analytics: UA-75674138-1
favicon: /favicon.png
twitter: yanni4night
google_plus: yanni4night@gmail.com
fb_admins:
fb_app_id: